### ISSUE TITLE
Separate issue and release caches

### ISSUE THREAD

**Issue by domcleal** [ehelms/tool_belt#10]
I'd find it useful to have separate release and issue caches.  I often want to be able to do multiple runs for a single release, either to split up my workload or for RCs (which use the same release).

If I could delete (or force a refresh of) the release cache without deleting the issue cache then I'd be able to pick up new tickets without needing to hammer Redmine for each issue number.

**Comment by ehelms** [comment]
Currently the issues are cache on a per project/release basis. If you look at https://github.com/ehelms/tool_belt/blob/master/lib/tool_belt/issue_cache.rb#L55 this is checking for the existence of a file with the project/release combination specified. You are wanting to break that down into segments based on another identifier? 

I could look at including timestamps or storing the issues individually with maybe symlinks to inner folders that make up a large 'release'.

**Comment by domcleal** [comment]
Storing issues individually would work, as then I could probably just delete the release file.  Is there any need for directories and symlinks for releases?  Can't issues just be stored independently of release?

**Comment by ehelms** [comment]
@domcleal I separated the issue and release cache in https://github.com/ehelms/tool_belt/pull/23 . The `--update-cache` option now only compares issue list from Redmine and current release manifest and downloads the diff. If it was preferred, I could make this update automatic instead of requiring passing `--update-cache`.

**Comment by domcleal** [comment]
Thanks, sorry I didn't get to testing it out in time.  I'll give it a go this week when preparing Foreman's next release.
